export enum EnvName {
    CONFIG_PATH = 'WS_SCRCPY_CONFIG',
    WS_SCRCPY_PATHNAME = 'WS_SCRCPY_PATHNAME',
    NOCODB_API_TOKEN = 'NOCODB_API_TOKEN',
    NOCODB_BASE_URL = 'NOCODB_BASE_URL',
    NOCODB_TABLE_ID = 'NOCODB_TABLE_ID',
}
